[template]
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"
keys = [ "/haproxy" ]
owner = "root"
mode = "0644"
check_cmd = "cat {{ .src }} && haproxy -f {{ .src }} -c"
reload_cmd = "kill -SIGHUP 1"
